### ISSUE TITLE
Specify SMD documentation and defaults for struct memebers through magic comments

### ISSUE THREAD

**Issue by smyrman** [semrush/zenrpc#33]
Take the following example:

```go
type MyService struct {} //zenrpc

type MyArg struct{
    A `json:"a"`
    B `json:"b"`
}

// DoSomething does something.
//zenrpc:arg specify a and b
func (MyService) DoSomehting(arg MyArg)

```
I don't see a documented way for providing documentaiton and/or defaults for argument `MyArg.A` and `MyArg.B` in the struct through magic comments or struct tags/comments.

It would be nice if it was somehow possible. Perhaps as method tags?

```go
//zenrpc:arg.a="default" Let's you document a.
```

**Comment by sergeyfast** [comment]
Please see https://github.com/semrush/zenrpc/blob/master/testdata/testdata_zenrpc.go#L103
from https://github.com/semrush/zenrpc/blob/master/testdata/model/model.go
Just add comments to fields like this:
```go
type MyArg struct{
    A int `json:"a"` // comment 1
    B int `json:"b"` // comment 2
}
```
